apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: vitaecareers 
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: vitaecareers
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: vitaecareers
    spec:
      containers:
      - name: nginx
        # Run this image
        image: sohamkashyap/vitaecareers:latest